// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelTo.Data;

#nullable disable

namespace TravelTo.Migrations
{
    [DbContext(typeof(ApplicationDataContext))]
    [Migration("20250208160443_kel")]
    partial class kel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TravelTo.Models.Company", b =>
                {
                    b.Property<int>("Company_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Company_Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("img_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("owner")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Company_Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Company_Id = 1,
                            Name = "TBCKVADRO",
                            description = "saswauli kompania romelic arasdros iarsebs",
                            img_name = "tbc_image.png",
                            owner = "gela"
                        },
                        new
                        {
                            Company_Id = 2,
                            Name = "liberti",
                            description = "raxdeba sh",
                            img_name = "liberti_img.png",
                            owner = "NEKA"
                        },
                        new
                        {
                            Company_Id = 3,
                            Name = "bog",
                            description = "imedia",
                            img_name = "bog_image.png",
                            owner = "NAK"
                        },
                        new
                        {
                            Company_Id = 4,
                            Name = "kripto",
                            description = "iarsebs",
                            img_name = "credit_bank.png",
                            owner = "bark"
                        });
                });

            modelBuilder.Entity("TravelTo.Models.ContactPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Messege")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Telephoni")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("gmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactiUndat");
                });

            modelBuilder.Entity("TravelTo.Models.SastumroCapitacity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CurrentCapacity")
                        .HasColumnType("int");

                    b.Property<int?>("MaxCapitacity")
                        .HasColumnType("int");

                    b.Property<int?>("Sastumro_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Sastumro_Id")
                        .IsUnique()
                        .HasFilter("[Sastumro_Id] IS NOT NULL");

                    b.ToTable("SastumroCapitacity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentCapacity = 0,
                            MaxCapitacity = 50,
                            Sastumro_Id = 1
                        },
                        new
                        {
                            Id = 2,
                            CurrentCapacity = 0,
                            MaxCapitacity = 100,
                            Sastumro_Id = 2
                        },
                        new
                        {
                            Id = 3,
                            CurrentCapacity = 0,
                            MaxCapitacity = 200,
                            Sastumro_Id = 3
                        },
                        new
                        {
                            Id = 4,
                            CurrentCapacity = 0,
                            MaxCapitacity = 300,
                            Sastumro_Id = 4
                        },
                        new
                        {
                            Id = 5,
                            CurrentCapacity = 0,
                            MaxCapitacity = 50,
                            Sastumro_Id = 5
                        },
                        new
                        {
                            Id = 6,
                            CurrentCapacity = 0,
                            MaxCapitacity = 200,
                            Sastumro_Id = 6
                        },
                        new
                        {
                            Id = 7,
                            CurrentCapacity = 0,
                            MaxCapitacity = 300,
                            Sastumro_Id = 7
                        },
                        new
                        {
                            Id = 8,
                            CurrentCapacity = 0,
                            MaxCapitacity = 300,
                            Sastumro_Id = 8
                        },
                        new
                        {
                            Id = 9,
                            CurrentCapacity = 0,
                            MaxCapitacity = 100,
                            Sastumro_Id = 9
                        },
                        new
                        {
                            Id = 10,
                            CurrentCapacity = 0,
                            MaxCapitacity = 2,
                            Sastumro_Id = 10
                        });
                });

            modelBuilder.Entity("TravelTo.Models.SastumroDajavshna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Phone_Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("text")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.HasKey("Id");

                    b.ToTable("sastumroDajavshna");
                });

            modelBuilder.Entity("TravelTo.Models.Sastumroebi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Fasi")
                        .HasColumnType("int");

                    b.Property<string>("Lokacia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nomer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tviseba_Id")
                        .HasColumnType("int");

                    b.Property<string>("gmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Tviseba_Id")
                        .IsUnique();

                    b.ToTable("Sastumroebis");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "ეს სასტუმრო წარმოადგენს სამგზის ლუქსს და თანამედროვე მომსახურებას.",
                            Fasi = 100,
                            Lokacia = "თბილისი",
                            Name = "თბილისის  სასტუმრო",
                            Tviseba_Id = 1,
                            gmail = "tbilisi@gmail.com",
                            image_name = "1.jpeg"
                        },
                        new
                        {
                            Id = 2,
                            Description = "ამ სასტუმროში სტუმრები სარგებლობენ საოცარი სანაპიროს ხედებით.",
                            Fasi = 50,
                            Lokacia = "ბათუმი",
                            Name = "ბათუმი რეზორტი",
                            Tviseba_Id = 2,
                            gmail = "batumi@gmail.com",
                            image_name = "2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Description = "სასტუმრო გთავაზობთ კომფორტულ პირობებს და შესანიშნავ სამზარეულოს.",
                            Fasi = 75,
                            Lokacia = "ქუთაისი",
                            Name = "ქუთაისი  სასტუმრო",
                            Tviseba_Id = 3,
                            gmail = "kutaisi@gmail.com",
                            image_name = "3.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Description = "სასტუმრო წარმოადგენს ისტორიულ და კულტურულ გარემოს.",
                            Fasi = 60,
                            Lokacia = "მცხეთა",
                            Name = "მცხეთა ჰერიტიჯ სასტუმრო",
                            Tviseba_Id = 4,
                            gmail = "mtskheta@gmail.com",
                            image_name = "4.webp"
                        },
                        new
                        {
                            Id = 5,
                            Description = "ცენტრალური ადგილმდებარეობა, ახლოს სამრეწველო და კულტურული ატრაქციონებთან.",
                            Fasi = 80,
                            Lokacia = "ზუგდიდი",
                            Name = "ზუგდიდი პარკ სასტუმრო",
                            Tviseba_Id = 5,
                            gmail = "zugdidi@gmail.com",
                            image_name = "5.jpg"
                        },
                        new
                        {
                            Id = 6,
                            Description = "მომსახურება მაღალი ხარისხის, მყუდრო ატმოსფერო და თანამედროვე ოთახები.",
                            Fasi = 40,
                            Lokacia = "გორი",
                            Name = "გორი ფორტეს სასტუმრო",
                            Tviseba_Id = 6,
                            gmail = "gori@gmail.com",
                            image_name = "6.jpg"
                        },
                        new
                        {
                            Id = 7,
                            Description = "თელავში მდებარე მყუდრო სასტუმრო, რომელიც გთავაზობთ შესანიშნავ მომსახურებას.",
                            Fasi = 30,
                            Lokacia = "თელავი",
                            Name = "თელავი უაინ ჰოტელი",
                            Tviseba_Id = 7,
                            gmail = "telavi@gmail.com",
                            image_name = "7.jpg"
                        },
                        new
                        {
                            Id = 8,
                            Description = "სასტუმრო მაღალი ხარისხის მომსახურებითა და ლამაზი ხედებით.",
                            Fasi = 45,
                            Lokacia = "სიღნაღი",
                            Name = "სიღნაღი ჰილტოპ სასტუმრო",
                            Tviseba_Id = 8,
                            gmail = "signagi@gmail.com",
                            image_name = "8.jpg"
                        },
                        new
                        {
                            Id = 9,
                            Description = "სასტუმრო მშვიდ გარემოში და სრულყოფილი მყუდროებით.",
                            Fasi = 55,
                            Lokacia = "რაჭა",
                            Name = "რაჭა რეზორტი",
                            Tviseba_Id = 9,
                            gmail = "racha@gmail.com",
                            image_name = "9.jpg"
                        },
                        new
                        {
                            Id = 10,
                            Description = "ვარძი ჰოტელი გთავაზობთ თანამედროვე ფასის ოპციებს და განსაცვიფრებელ გარემოს.",
                            Fasi = 65,
                            Lokacia = "ვარძი",
                            Name = "ვარძი რეზორტი",
                            Tviseba_Id = 10,
                            gmail = "vardzi@gmail.com",
                            image_name = "10.jpg"
                        });
                });

            modelBuilder.Entity("TravelTo.Models.SastumroebiDaTurebi", b =>
                {
                    b.Property<int>("Sastumro_Id")
                        .HasColumnType("int");

                    b.Property<int>("Turebi_Id")
                        .HasColumnType("int");

                    b.HasKey("Sastumro_Id", "Turebi_Id");

                    b.HasIndex("Turebi_Id");

                    b.ToTable("SastumroebiDaTurebi");

                    b.HasData(
                        new
                        {
                            Sastumro_Id = 2,
                            Turebi_Id = 1
                        },
                        new
                        {
                            Sastumro_Id = 3,
                            Turebi_Id = 2
                        },
                        new
                        {
                            Sastumro_Id = 4,
                            Turebi_Id = 3
                        },
                        new
                        {
                            Sastumro_Id = 1,
                            Turebi_Id = 8
                        },
                        new
                        {
                            Sastumro_Id = 10,
                            Turebi_Id = 4
                        },
                        new
                        {
                            Sastumro_Id = 9,
                            Turebi_Id = 7
                        },
                        new
                        {
                            Sastumro_Id = 8,
                            Turebi_Id = 6
                        },
                        new
                        {
                            Sastumro_Id = 5,
                            Turebi_Id = 5
                        });
                });

            modelBuilder.Entity("TravelTo.Models.SastumtroAndDajavshna", b =>
                {
                    b.Property<int>("Sastumro_Id")
                        .HasColumnType("int");

                    b.Property<int>("SastumroDajavshna_Id")
                        .HasColumnType("int");

                    b.HasKey("Sastumro_Id", "SastumroDajavshna_Id");

                    b.HasIndex("SastumroDajavshna_Id");

                    b.ToTable("SastumtroAndDajavshna");
                });

            modelBuilder.Entity("TravelTo.Models.Turebi", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Company_Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("image_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Company_Id");

                    b.ToTable("Turebis");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Company_Id = 1,
                            Description = "ანტარქტიდა დედამიწის ყველაზე სამხრეთული კონტინენტია, სადაც არ არსებობს მუდმივი მოსახლეობა, მხოლოდ მკვლევარები.",
                            Name = "ანტარქტიდა",
                            Price = 999.99000000000001,
                            image_name = "antarqtida.jpg"
                        },
                        new
                        {
                            id = 2,
                            Company_Id = 3,
                            Description = "თბილისი საქართველოს დედაქალაქია, ცნობილია თავისი ისტორიული ძველი უბნებით და კულტურული მნიშვნელობით.",
                            Name = "თბილისი",
                            Price = 500.99000000000001,
                            image_name = "Tbilisi.jpg"
                        },
                        new
                        {
                            id = 3,
                            Company_Id = 2,
                            Description = "ქუთაისი საქართველოს ისტორიული ქალაქია, გალიას საკათედრო ტაძრითა და მსოფლიოს ერთ-ერთი ძველი უნივერსიტეტით.",
                            Name = "ქუთაისი",
                            Price = 799.99000000000001,
                            image_name = "7012519385_f7e92b8d8e_z.jpg"
                        },
                        new
                        {
                            id = 4,
                            Company_Id = 4,
                            Description = "პარიზი საფრანგეთის დედაქალაქია, ცნობილია აიფელის კოშკით და ლუვრის მუზეუმით.",
                            Name = "პარიზი",
                            Price = 1999.99,
                            image_name = "Spain.jfif"
                        },
                        new
                        {
                            id = 5,
                            Company_Id = 1,
                            Description = "ბათუმი შავი ზღვის სანაპიროზე მდებარე ქალაქია, ცნობილი თავისი სანაპირო პარკებით და კურორტებით.",
                            Name = "ბათუმი",
                            Price = 999.99000000000001,
                            image_name = "Batumi.jpg"
                        },
                        new
                        {
                            id = 6,
                            Company_Id = 2,
                            Description = "მაიამი, აშშ-ის ფლორიდაში მდებარე ქალაქია, ცნობილი თავისი ფინანსური, კულტურული და სავაჭრო ცენტრის როლით.",
                            Name = "მაიამი",
                            Price = 1999.99,
                            image_name = "Brazil.jfif"
                        },
                        new
                        {
                            id = 7,
                            Company_Id = 4,
                            Description = "გორი ქალაქია საქართველოში, ცნობილია თავისი ისტორიული მნიშვნელობით და გორის ციხით.",
                            Name = "გორი",
                            Price = 500.99000000000001,
                            image_name = "Denmark.jfif"
                        },
                        new
                        {
                            id = 8,
                            Company_Id = 3,
                            Description = "თელავი ქალაქია კახეთში, ცნობილი თავისი ღვინის კულტურით და ისტორიული ძეგლებით.",
                            Name = "თელავი",
                            Price = 999.99000000000001,
                            image_name = "Los-AngelesCa.jfif"
                        });
                });

            modelBuilder.Entity("TravelTo.Models.TvisebebiSastumroebis", b =>
                {
                    b.Property<int>("Tviseba_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Tviseba_Id"));

                    b.Property<string>("Wifi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ბარი")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ბაღი")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ბილიარდი")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("კინოდარბაზი")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ოთახი_არამწეველებისთვის")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("რესტორანი")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("საბავშო_ოთახი")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("საკონფერენციო_დარბაზი")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("სამრეცხაო")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("საუნა")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("სპა_ცენტრი")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("სპორტული_დარბაზი")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ტერასა")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("უფასო_ავტოსადგომი")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("უფასო_წყალი")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("შინაური_ცხოვრების_დაშვება")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Tviseba_Id");

                    b.ToTable("TvisebebiDaSastumroebi");

                    b.HasData(
                        new
                        {
                            Tviseba_Id = 1,
                            Wifi = "YES",
                            ბარი = "YES",
                            ბაღი = "YES",
                            ბილიარდი = "NO",
                            კინოდარბაზი = "NO",
                            ოთახი_არამწეველებისთვის = "NO",
                            რესტორანი = "NO",
                            საბავშო_ოთახი = "YES",
                            საკონფერენციო_დარბაზი = "NO",
                            სამრეცხაო = "YES",
                            საუნა = "YES",
                            სპა_ცენტრი = "NO",
                            სპორტული_დარბაზი = "YES",
                            ტერასა = "NO",
                            უფასო_ავტოსადგომი = "NO",
                            უფასო_წყალი = "NO",
                            შინაური_ცხოვრების_დაშვება = "YES"
                        },
                        new
                        {
                            Tviseba_Id = 2,
                            Wifi = "NO",
                            ბარი = "NO",
                            ბაღი = "NO",
                            ბილიარდი = "YES",
                            კინოდარბაზი = "YES",
                            ოთახი_არამწეველებისთვის = "YES",
                            რესტორანი = "YES",
                            საბავშო_ოთახი = "NO",
                            საკონფერენციო_დარბაზი = "YES",
                            სამრეცხაო = "NO",
                            საუნა = "NO",
                            სპა_ცენტრი = "YES",
                            სპორტული_დარბაზი = "NO",
                            ტერასა = "YES",
                            უფასო_ავტოსადგომი = "YES",
                            უფასო_წყალი = "YES",
                            შინაური_ცხოვრების_დაშვება = "NO"
                        },
                        new
                        {
                            Tviseba_Id = 3,
                            Wifi = "YES",
                            ბარი = "YES",
                            ბაღი = "YES",
                            ბილიარდი = "NO",
                            კინოდარბაზი = "YES",
                            ოთახი_არამწეველებისთვის = "NO",
                            რესტორანი = "NO",
                            საბავშო_ოთახი = "YES",
                            საკონფერენციო_დარბაზი = "NO",
                            სამრეცხაო = "YES",
                            საუნა = "YES",
                            სპა_ცენტრი = "NO",
                            სპორტული_დარბაზი = "YES",
                            ტერასა = "NO",
                            უფასო_ავტოსადგომი = "NO",
                            უფასო_წყალი = "NO",
                            შინაური_ცხოვრების_დაშვება = "YES"
                        },
                        new
                        {
                            Tviseba_Id = 4,
                            Wifi = "YES",
                            ბარი = "NO",
                            ბაღი = "NO",
                            ბილიარდი = "YES",
                            კინოდარბაზი = "NO",
                            ოთახი_არამწეველებისთვის = "NO",
                            რესტორანი = "YES",
                            საბავშო_ოთახი = "YES",
                            საკონფერენციო_დარბაზი = "YES",
                            სამრეცხაო = "YES",
                            საუნა = "YES",
                            სპა_ცენტრი = "YES",
                            სპორტული_დარბაზი = "NO",
                            ტერასა = "YES",
                            უფასო_ავტოსადგომი = "YES",
                            უფასო_წყალი = "NO",
                            შინაური_ცხოვრების_დაშვება = "NO"
                        },
                        new
                        {
                            Tviseba_Id = 5,
                            Wifi = "NO",
                            ბარი = "YES",
                            ბაღი = "YES",
                            ბილიარდი = "YES",
                            კინოდარბაზი = "YES",
                            ოთახი_არამწეველებისთვის = "YES",
                            რესტორანი = "NO",
                            საბავშო_ოთახი = "YES",
                            საკონფერენციო_დარბაზი = "NO",
                            სამრეცხაო = "NO",
                            საუნა = "NO",
                            სპა_ცენტრი = "NO",
                            სპორტული_დარბაზი = "YES",
                            ტერასა = "YES",
                            უფასო_ავტოსადგომი = "NO",
                            უფასო_წყალი = "YES",
                            შინაური_ცხოვრების_დაშვება = "YES"
                        },
                        new
                        {
                            Tviseba_Id = 6,
                            Wifi = "YES",
                            ბარი = "YES",
                            ბაღი = "NO",
                            ბილიარდი = "NO",
                            კინოდარბაზი = "YES",
                            ოთახი_არამწეველებისთვის = "NO",
                            რესტორანი = "YES",
                            საბავშო_ოთახი = "NO",
                            საკონფერენციო_დარბაზი = "NO",
                            სამრეცხაო = "YES",
                            საუნა = "YES",
                            სპა_ცენტრი = "NO",
                            სპორტული_დარბაზი = "YES",
                            ტერასა = "NO",
                            უფასო_ავტოსადგომი = "YES",
                            უფასო_წყალი = "NO",
                            შინაური_ცხოვრების_დაშვება = "YES"
                        },
                        new
                        {
                            Tviseba_Id = 7,
                            Wifi = "NO",
                            ბარი = "NO",
                            ბაღი = "YES",
                            ბილიარდი = "YES",
                            კინოდარბაზი = "NO",
                            ოთახი_არამწეველებისთვის = "YES",
                            რესტორანი = "YES",
                            საბავშო_ოთახი = "YES",
                            საკონფერენციო_დარბაზი = "YES",
                            სამრეცხაო = "YES",
                            საუნა = "NO",
                            სპა_ცენტრი = "YES",
                            სპორტული_დარბაზი = "NO",
                            ტერასა = "YES",
                            უფასო_ავტოსადგომი = "NO",
                            უფასო_წყალი = "NO",
                            შინაური_ცხოვრების_დაშვება = "NO"
                        },
                        new
                        {
                            Tviseba_Id = 8,
                            Wifi = "YES",
                            ბარი = "YES",
                            ბაღი = "NO",
                            ბილიარდი = "YES",
                            კინოდარბაზი = "YES",
                            ოთახი_არამწეველებისთვის = "NO",
                            რესტორანი = "NO",
                            საბავშო_ოთახი = "YES",
                            საკონფერენციო_დარბაზი = "NO",
                            სამრეცხაო = "YES",
                            საუნა = "YES",
                            სპა_ცენტრი = "YES",
                            სპორტული_დარბაზი = "NO",
                            ტერასა = "NO",
                            უფასო_ავტოსადგომი = "YES",
                            უფასო_წყალი = "NO",
                            შინაური_ცხოვრების_დაშვება = "NO"
                        },
                        new
                        {
                            Tviseba_Id = 9,
                            Wifi = "NO",
                            ბარი = "NO",
                            ბაღი = "YES",
                            ბილიარდი = "NO",
                            კინოდარბაზი = "YES",
                            ოთახი_არამწეველებისთვის = "YES",
                            რესტორანი = "YES",
                            საბავშო_ოთახი = "NO",
                            საკონფერენციო_დარბაზი = "YES",
                            სამრეცხაო = "YES",
                            საუნა = "NO",
                            სპა_ცენტრი = "NO",
                            სპორტული_დარბაზი = "YES",
                            ტერასა = "YES",
                            უფასო_ავტოსადგომი = "NO",
                            უფასო_წყალი = "YES",
                            შინაური_ცხოვრების_დაშვება = "YES"
                        },
                        new
                        {
                            Tviseba_Id = 10,
                            Wifi = "YES",
                            ბარი = "YES",
                            ბაღი = "NO",
                            ბილიარდი = "YES",
                            კინოდარბაზი = "YES",
                            ოთახი_არამწეველებისთვის = "NO",
                            რესტორანი = "NO",
                            საბავშო_ოთახი = "YES",
                            საკონფერენციო_დარბაზი = "NO",
                            სამრეცხაო = "YES",
                            საუნა = "NO",
                            სპა_ცენტრი = "YES",
                            სპორტული_დარბაზი = "NO",
                            ტერასა = "NO",
                            უფასო_ავტოსადგომი = "YES",
                            უფასო_წყალი = "YES",
                            შინაური_ცხოვრების_დაშვება = "NO"
                        });
                });

            modelBuilder.Entity("TravelTo.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("First_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Last_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TravelTo.Models.UserAndSastumroebi", b =>
                {
                    b.Property<int?>("Sastumorebi_Id")
                        .HasColumnType("int");

                    b.Property<string>("User_Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Sastumorebi_Id", "User_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("userAndSastumroebis");
                });

            modelBuilder.Entity("TravelTo.Models.UserAndTurebiMap", b =>
                {
                    b.Property<int?>("Turebi_Id")
                        .HasColumnType("int");

                    b.Property<string>("User_Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Turebi_Id", "User_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("UserAndTurebi");
                });

            modelBuilder.Entity("TravelTo.Models.UserCookie", b =>
                {
                    b.Property<string>("User_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("expires_in")
                        .HasColumnType("date");

                    b.HasKey("User_Id");

                    b.ToTable("userCookies");
                });

            modelBuilder.Entity("TravelTo.Models.UserCookieTurebi", b =>
                {
                    b.Property<int?>("Turebi_Id")
                        .HasColumnType("int");

                    b.Property<string>("User_Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Turebi_Id", "User_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("userCookieTurebis");
                });

            modelBuilder.Entity("TravelTo.Models.UserSastumroebiCookies", b =>
                {
                    b.Property<int?>("Sastumro_Id")
                        .HasColumnType("int");

                    b.Property<string>("User_Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Sastumro_Id", "User_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("userSastumroebiCookies");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TravelTo.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TravelTo.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelTo.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TravelTo.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelTo.Models.SastumroCapitacity", b =>
                {
                    b.HasOne("TravelTo.Models.Sastumroebi", "Sastumroebi")
                        .WithOne("sastumroCapitacity")
                        .HasForeignKey("TravelTo.Models.SastumroCapitacity", "Sastumro_Id");

                    b.Navigation("Sastumroebi");
                });

            modelBuilder.Entity("TravelTo.Models.Sastumroebi", b =>
                {
                    b.HasOne("TravelTo.Models.TvisebebiSastumroebis", "tvisebebiSastumroebis")
                        .WithOne("Sastumro")
                        .HasForeignKey("TravelTo.Models.Sastumroebi", "Tviseba_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tvisebebiSastumroebis");
                });

            modelBuilder.Entity("TravelTo.Models.SastumroebiDaTurebi", b =>
                {
                    b.HasOne("TravelTo.Models.Sastumroebi", "Sastumroebi")
                        .WithMany("turebi")
                        .HasForeignKey("Sastumro_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelTo.Models.Turebi", "Turebi")
                        .WithMany("Sastumroebi")
                        .HasForeignKey("Turebi_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sastumroebi");

                    b.Navigation("Turebi");
                });

            modelBuilder.Entity("TravelTo.Models.SastumtroAndDajavshna", b =>
                {
                    b.HasOne("TravelTo.Models.SastumroDajavshna", "sastumroDajavshna")
                        .WithMany("SastumroAndDajavshna")
                        .HasForeignKey("SastumroDajavshna_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelTo.Models.Sastumroebi", "Sastumroebi")
                        .WithMany("SastumroAndDajavshna")
                        .HasForeignKey("Sastumro_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sastumroebi");

                    b.Navigation("sastumroDajavshna");
                });

            modelBuilder.Entity("TravelTo.Models.Turebi", b =>
                {
                    b.HasOne("TravelTo.Models.Company", "Company")
                        .WithMany("Turebi")
                        .HasForeignKey("Company_Id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("TravelTo.Models.UserAndSastumroebi", b =>
                {
                    b.HasOne("TravelTo.Models.Sastumroebi", "sastumroebi")
                        .WithMany("user_sastumroebi")
                        .HasForeignKey("Sastumorebi_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelTo.Models.User", "users")
                        .WithMany("user_sastumroebi")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("sastumroebi");

                    b.Navigation("users");
                });

            modelBuilder.Entity("TravelTo.Models.UserAndTurebiMap", b =>
                {
                    b.HasOne("TravelTo.Models.Turebi", "turebi")
                        .WithMany("UserAndTurebiMapT")
                        .HasForeignKey("Turebi_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelTo.Models.User", "User")
                        .WithMany("UserAndTurebiMapU")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("turebi");
                });

            modelBuilder.Entity("TravelTo.Models.UserCookieTurebi", b =>
                {
                    b.HasOne("TravelTo.Models.Turebi", "Turebi")
                        .WithMany("UserCookieTurebi")
                        .HasForeignKey("Turebi_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelTo.Models.UserCookie", "UserCookie")
                        .WithMany("UserCookieTurebis")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turebi");

                    b.Navigation("UserCookie");
                });

            modelBuilder.Entity("TravelTo.Models.UserSastumroebiCookies", b =>
                {
                    b.HasOne("TravelTo.Models.Sastumroebi", "Sastumroebi")
                        .WithMany("sastumroAndCookies")
                        .HasForeignKey("Sastumro_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelTo.Models.UserCookie", "UserCookie")
                        .WithMany("UserSastumroebiCookies")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sastumroebi");

                    b.Navigation("UserCookie");
                });

            modelBuilder.Entity("TravelTo.Models.Company", b =>
                {
                    b.Navigation("Turebi");
                });

            modelBuilder.Entity("TravelTo.Models.SastumroDajavshna", b =>
                {
                    b.Navigation("SastumroAndDajavshna");
                });

            modelBuilder.Entity("TravelTo.Models.Sastumroebi", b =>
                {
                    b.Navigation("SastumroAndDajavshna");

                    b.Navigation("sastumroAndCookies");

                    b.Navigation("sastumroCapitacity");

                    b.Navigation("turebi");

                    b.Navigation("user_sastumroebi");
                });

            modelBuilder.Entity("TravelTo.Models.Turebi", b =>
                {
                    b.Navigation("Sastumroebi");

                    b.Navigation("UserAndTurebiMapT");

                    b.Navigation("UserCookieTurebi");
                });

            modelBuilder.Entity("TravelTo.Models.TvisebebiSastumroebis", b =>
                {
                    b.Navigation("Sastumro")
                        .IsRequired();
                });

            modelBuilder.Entity("TravelTo.Models.User", b =>
                {
                    b.Navigation("UserAndTurebiMapU");

                    b.Navigation("user_sastumroebi");
                });

            modelBuilder.Entity("TravelTo.Models.UserCookie", b =>
                {
                    b.Navigation("UserCookieTurebis");

                    b.Navigation("UserSastumroebiCookies");
                });
#pragma warning restore 612, 618
        }
    }
}
