// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelTo.Data;

#nullable disable

namespace TravelTo.Migrations.ApplicationData
{
    [DbContext(typeof(ApplicationDataContext))]
    partial class ApplicationDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelTo.Models.Company", b =>
                {
                    b.Property<int>("Company_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Company_Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("owner")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Company_Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Company_Id = 1,
                            Name = "BOG"
                        },
                        new
                        {
                            Company_Id = 2,
                            Name = "TBC"
                        });
                });

            modelBuilder.Entity("TravelTo.Models.Turebi", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Company_Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("image_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Company_Id");

                    b.ToTable("Turebis");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Company_Id = 1,
                            Description = "aq iyo batoni wyali romelmac wyali dalia",
                            Name = "Antarqtida",
                            Price = 5.9900000000000002,
                            image_name = "31394_1.jpg"
                        },
                        new
                        {
                            id = 2,
                            Company_Id = 2,
                            Description = "tbilo tibifli",
                            Name = "Tbilisi",
                            Price = 15.99,
                            image_name = "59564_1.jpg"
                        },
                        new
                        {
                            id = 3,
                            Company_Id = 2,
                            Description = "parizelta dedaqali",
                            Name = "Parizi",
                            Price = 6.9900000000000002,
                            image_name = "59564_1.jpg"
                        });
                });

            modelBuilder.Entity("TravelTo.Models.Turebi", b =>
                {
                    b.HasOne("TravelTo.Models.Company", "Company")
                        .WithMany("Turebi")
                        .HasForeignKey("Company_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("TravelTo.Models.Company", b =>
                {
                    b.Navigation("Turebi");
                });
#pragma warning restore 612, 618
        }
    }
}
